const DADOS_INICIAIS = {
  "escritorio": "EZ Brokers - 7º Pavimento - Rua Cubatão, 320",
  "atualizado_em": "",
  "bancadas": [
    { "id": 1, "numero": "1", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 2, "numero": "2", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 3, "numero": "3", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 4, "numero": "4", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 5, "numero": "5", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 6, "numero": "6", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 7, "numero": "7", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 8, "numero": "8", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 9, "numero": "9", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 10, "numero": "10", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 11, "numero": "11", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 12, "numero": "12", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 13, "numero": "13", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 14, "numero": "14", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 15, "numero": "15", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 16, "numero": "16", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 17, "numero": "17", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 18, "numero": "18", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 19, "numero": "19", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 20, "numero": "20", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 21, "numero": "21", "ramal": "", "area": "Fileira Superior", "ativos": [], "zona": null },
    { "id": 22, "numero": "22", "ramal": "", "area": "Bloco A", "ativos": [], "zona": null },
    { "id": 23, "numero": "23", "ramal": "", "area": "Bloco A", "ativos": [], "zona": null },
    { "id": 24, "numero": "24", "ramal": "", "area": "Bloco A", "ativos": [], "zona": null },
    { "id": 25, "numero": "25", "ramal": "", "area": "Bloco A", "ativos": [], "zona": null },
    { "id": 26, "numero": "26", "ramal": "", "area": "Bloco A", "ativos": [], "zona": null },
    { "id": 27, "numero": "27", "ramal": "", "area": "Bloco A", "ativos": [], "zona": null },
    { "id": 28, "numero": "28", "ramal": "", "area": "Bloco A", "ativos": [], "zona": null },
    { "id": 29, "numero": "29", "ramal": "", "area": "Bloco A", "ativos": [], "zona": null },
    { "id": 30, "numero": "30", "ramal": "", "area": "Bloco A", "ativos": [], "zona": null },
    { "id": 31, "numero": "31", "ramal": "", "area": "Bloco A", "ativos": [], "zona": null },
    { "id": 32, "numero": "32", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 33, "numero": "33", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 34, "numero": "34", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 35, "numero": "35", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 36, "numero": "36", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 37, "numero": "37", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 38, "numero": "38", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 39, "numero": "39", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 40, "numero": "40", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 41, "numero": "41", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 42, "numero": "42", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 43, "numero": "43", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 44, "numero": "44", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 45, "numero": "45", "ramal": "", "area": "Bloco B", "ativos": [], "zona": null },
    { "id": 46, "numero": "46", "ramal": "", "area": "Bloco C", "ativos": [], "zona": null },
    { "id": 47, "numero": "47", "ramal": "", "area": "Bloco C", "ativos": [], "zona": null },
    { "id": 48, "numero": "48", "ramal": "", "area": "Bloco C", "ativos": [], "zona": null },
    { "id": 49, "numero": "49", "ramal": "", "area": "Bloco C", "ativos": [], "zona": null },
    { "id": 50, "numero": "50", "ramal": "", "area": "Bloco C", "ativos": [], "zona": null },
    { "id": 51, "numero": "51", "ramal": "", "area": "Bloco C", "ativos": [], "zona": null },
    { "id": 52, "numero": "52", "ramal": "", "area": "Bloco C", "ativos": [], "zona": null },
    { "id": 53, "numero": "53", "ramal": "", "area": "Bloco C", "ativos": [], "zona": null },
    { "id": 54, "numero": "54", "ramal": "", "area": "Bloco C", "ativos": [], "zona": null },
    { "id": 55, "numero": "55", "ramal": "", "area": "Bloco C", "ativos": [], "zona": null },
    { "id": 56, "numero": "56", "ramal": "", "area": "Bloco C", "ativos": [], "zona": null },
    { "id": 57, "numero": "57", "ramal": "", "area": "Bloco C", "ativos": [], "zona": null },
    { "id": 58, "numero": "58", "ramal": "", "area": "Bloco D", "ativos": [], "zona": null },
    { "id": 59, "numero": "59", "ramal": "", "area": "Bloco D", "ativos": [], "zona": null },
    { "id": 60, "numero": "60", "ramal": "", "area": "Bloco D", "ativos": [], "zona": null },
    { "id": 61, "numero": "61", "ramal": "", "area": "Bloco D", "ativos": [], "zona": null },
    { "id": 62, "numero": "62", "ramal": "", "area": "Bloco D", "ativos": [], "zona": null },
    { "id": 63, "numero": "63", "ramal": "", "area": "Bloco D", "ativos": [], "zona": null },
    { "id": 64, "numero": "64", "ramal": "", "area": "Bloco D", "ativos": [], "zona": null },
    { "id": 65, "numero": "65", "ramal": "", "area": "Bloco D", "ativos": [], "zona": null },
    { "id": 66, "numero": "66", "ramal": "", "area": "Bloco D", "ativos": [], "zona": null },
    { "id": 67, "numero": "67", "ramal": "", "area": "Bloco D", "ativos": [], "zona": null },
    { "id": 68, "numero": "68", "ramal": "", "area": "Bloco D", "ativos": [], "zona": null },
    { "id": 69, "numero": "69", "ramal": "", "area": "Bloco D", "ativos": [], "zona": null },
    { "id": 70, "numero": "70", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 71, "numero": "71", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 72, "numero": "72", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 73, "numero": "73", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 74, "numero": "74", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 75, "numero": "75", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 76, "numero": "76", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 77, "numero": "77", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 78, "numero": "78", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 79, "numero": "79", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 80, "numero": "80", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 81, "numero": "81", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 82, "numero": "82", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 83, "numero": "83", "ramal": "", "area": "Bloco E", "ativos": [], "zona": null },
    { "id": 84, "numero": "84", "ramal": "", "area": "Bloco F", "ativos": [], "zona": null },
    { "id": 85, "numero": "85", "ramal": "", "area": "Bloco F", "ativos": [], "zona": null },
    { "id": 86, "numero": "86", "ramal": "", "area": "Bloco F", "ativos": [], "zona": null },
    { "id": 87, "numero": "87", "ramal": "", "area": "Bloco F", "ativos": [], "zona": null },
    { "id": 88, "numero": "88", "ramal": "", "area": "Bloco F", "ativos": [], "zona": null },
    { "id": 89, "numero": "89", "ramal": "", "area": "Bloco F", "ativos": [], "zona": null },
    { "id": 90, "numero": "90", "ramal": "", "area": "Bloco F", "ativos": [], "zona": null },
    { "id": 91, "numero": "91", "ramal": "", "area": "Bloco F", "ativos": [], "zona": null },
    { "id": 92, "numero": "92", "ramal": "", "area": "Bloco F", "ativos": [], "zona": null },
    { "id": 93, "numero": "93", "ramal": "", "area": "Bloco F", "ativos": [], "zona": null },
    { "id": 94, "numero": "94", "ramal": "", "area": "Bloco F", "ativos": [], "zona": null },
    { "id": 95, "numero": "95", "ramal": "", "area": "Bloco F", "ativos": [], "zona": null },

    { "id": 200, "numero": "", "ramal": "", "area": "Rack de TI", "ativos": [], "zona": null },

    { "id": 201, "numero": "", "ramal": "", "area": "Reunião 02", "ativos": [], "zona": null },
    { "id": 202, "numero": "", "ramal": "", "area": "Reunião 01", "ativos": [], "zona": null },

    { "id": 250, "numero": "", "ramal": "", "area": "Recepção", "ativos": [], "zona": null },

    { "id": 211, "numero": "1", "ramal": "", "area": "Superintendência", "ativos": [], "zona": null },
    { "id": 212, "numero": "2", "ramal": "", "area": "Superintendência", "ativos": [], "zona": null },
    { "id": 213, "numero": "3", "ramal": "", "area": "Superintendência", "ativos": [], "zona": null },
    { "id": 214, "numero": "4", "ramal": "", "area": "Superintendência", "ativos": [], "zona": null },

    { "id": 221, "numero": "1", "ramal": "", "area": "ADM", "ativos": [], "zona": null },
    { "id": 222, "numero": "2", "ramal": "", "area": "ADM", "ativos": [], "zona": null },
    { "id": 223, "numero": "3", "ramal": "", "area": "ADM", "ativos": [], "zona": null },
    { "id": 224, "numero": "4", "ramal": "", "area": "ADM", "ativos": [], "zona": null },
    { "id": 225, "numero": "5", "ramal": "", "area": "ADM", "ativos": [], "zona": null },
    { "id": 226, "numero": "6", "ramal": "", "area": "ADM", "ativos": [], "zona": null },
    { "id": 227, "numero": "7", "ramal": "", "area": "ADM", "ativos": [], "zona": null },
    { "id": 228, "numero": "8", "ramal": "", "area": "ADM", "ativos": [], "zona": null },

    { "id": 241, "numero": "1", "ramal": "", "area": "Jurídico", "ativos": [], "zona": null },
    { "id": 242, "numero": "2", "ramal": "", "area": "Jurídico", "ativos": [], "zona": null },
    { "id": 243, "numero": "3", "ramal": "", "area": "Jurídico", "ativos": [], "zona": null },
    { "id": 244, "numero": "4", "ramal": "", "area": "Jurídico", "ativos": [], "zona": null },
    { "id": 245, "numero": "5", "ramal": "", "area": "Jurídico", "ativos": [], "zona": null },
    { "id": 246, "numero": "6", "ramal": "", "area": "Jurídico", "ativos": [], "zona": null },
    { "id": 247, "numero": "7", "ramal": "", "area": "Jurídico", "ativos": [], "zona": null },
    { "id": 248, "numero": "8", "ramal": "", "area": "Jurídico", "ativos": [], "zona": null },

    { "id": 231, "numero": "1", "ramal": "", "area": "Diretoria", "ativos": [], "zona": null },
    { "id": 232, "numero": "2", "ramal": "", "area": "Diretoria", "ativos": [], "zona": null },
    { "id": 233, "numero": "3", "ramal": "", "area": "Diretoria", "ativos": [], "zona": null }
  ]
};
